### PR TITLE
Use region & endpoint options in s3 storage client from credentials.

### LINKED ISSUE #11: Bucket access AWS region related problem
**Describe the bug**
If nimbella is deployed in AWS in a generic region (for example `eu-south-1`) you get an error

```
An error occurred (IllegalLocationConstraintException) when calling the PutObject operation: The eu-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.
```

**To Reproduce**
1. Install nimbella in AWS in another region (for example EKSItaly is in eu-south-1)
2. Run this code:
```
def main(arg):
    try:
        bucket = nimbella.storage()
        filename = "test.txt"
        file = bucket.file(filename)
        file.save('Expected %s contents' % filename, 'text/plain')
        return { "ok": True}
    except Exception as e:
        return { "error": str(e) }
```

3.

**Expected behavior**
ok: True

**Screenshots**

Extra informations:

This is what the __NIM_STORAGE_KEY looks like (stripped down of credentials)

```
NIM_STORAGE_KEY="{\"provider\":\"@nimbella/storage-s3\",\"region\":\"eu-south-1\",\"endpoint\":\"\",\"weburl\":\"https://iogw-eksitaly.nimbella.io\",\"cloudfrontId\":\"XXXX\",\"iamUser\":\"app-buckets-iogw-Y0avZmVH\",\"policyArn\":\"arn:aws:iam::332320267357:policy/app-buckets-iogw-Y0avZmVH\",\"credentials\":{\"accessKeyId\":\"XXX\",\"secretAccessKey\":\"jXXX"}}"
```

### PR DESCRIPTION
**Pull request by jthomas**
Fixes #11

### CODE REVIEW

**Review by rabbah — APPROVED** [review]

**Review by sciabarracom — COMMENTED** [review]
this is more or less what I tried to do in the first place but did not work

**Comment by jthomas** [comment]
I've also now added support for a custom "endpoint".

**Comment by jthomas** [comment]
Will wait for confirmation this fixes the issue for @sciabarracom before merging.

**Review by rabbah — APPROVED** [review]

**Comment by sciabarracom** [comment]
It works for me in EKS Italy

**Pull request merged**
